AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  TableName:
    Type: String
Globals:
  Function:
    Runtime: python3.7
    Timeout: 300
    MemorySize: 128
Resources:
  IngestApplication:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      Timeout: 300
      MemorySize: 128
      Policies:
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref TableName
      Events:
        InvokePeriodicValues:
          Type: Schedule
          Properties:
            Input: '{"operation": "test"}'
            Schedule: cron(15,45 * * * ? *)
      Layers:
        - arn:aws:lambda:ap-northeast-1:249908578461:layer:AWSLambda-Python37-SciPy1x:38
        - arn:aws:lambda:ap-northeast-1:251344623468:layer:my-Python37-Pandas112:1
